### ISSUE TITLE
Please consider reverting to 6-digit version numbers

### ISSUE THREAD

**Issue by pghmcfc** [plicease/Test-Version#1]
Please consider reverting to version numbers with six digits after the dot, at least until you issue version 2. Some downstream packaging systems (e.g. rpm, maybe deb) have semantic version numbering schemes where 1.004001 is treated the same as 1.4001 and hence "later" than 1.05. If you stick with six digits after the dot, perl version numbering and semantic version numbering will have the same ordering and won't require workarounds downstream.

Alternatively, bump the major release version to 2 and then use as many digits as you like, but please stick to the same number of digits for each major release. This makes life easier for downstream packagers.

Thank you.

**Comment by plicease** [comment]
I really find the semantic versioning to be overly complicated, which is why I am chucking that.  I can bump to 2 in the next version though.

**Comment by pghmcfc** [comment]
That'd be great, thanks.

**Comment by plicease** [comment]
Should be resolved with the release of 2.00
