### ISSUE TITLE
filename_match?

### ISSUE THREAD

**Issue by karenetheridge** [plicease/Test-Version#2]
I saw you just added `filename_match`. Instead of inventing a new system for matching files, why not make use of the excellent filefinder hooks already available in core?

LDist::Zilla::Role::FileFinderUser/default_finders
L<[FileFinder::ByName]|Dist::Zilla::Plugin::FileFinder::ByName>
L<[FileFinder::Filter]|Dist::Zilla::Plugin::FileFinder::Filter>

**Comment by plicease** [comment]
Not sure how that works without `Dist::Zilla`.

**Comment by karenetheridge** [comment]
lol sorry, total mental blank there. :D :D

In other Test::\* modules that get pulled in via a dzil plugin, I've simply added a 'filenames' option, and make the plugin do the heavy lifting of selecting the files to be tested.

**Comment by plicease** [comment]
No problem.  Actually I think a similar feature would make sense for Dist::Zilla::Plugin::Test::Version ... if I get time I will add it.  It wouldn't work for my particular use case, but others may find it useful.

**Comment by karenetheridge** [comment]
_nod_

Glad to see you picked up those modules... I was going to yoink them, but I haven't used them recently so I was going to wait to see if there was someone more keen :)
