### ISSUE TITLE
Should require Module::Metadata 1.000020

### ISSUE THREAD

**Issue by autarch** [plicease/Test-Version#7]
Otherwise the ignore_unindexable feature simply doesn't work, causing confusing test failures. See https://travis-ci.org/autarch/DateTime-Locale/jobs/160587730 for an example.

Is there any reason not to simply bump the prereq?

**Comment by plicease** [comment]
I can't think of any reason not to.  2.05 is on its way to CPAN.

**Comment by autarch** [comment]
Thanks!
